apiVersion: v1
name: tech-talk
version: 0.0.1
appVersion:
description: Helm chart for tech-talk
keywords:
  - tech-talk
sources:
  - https://github.com/TechTalkFridays/tech-talk-src.git
engine: gotpl
maintainers:
- name: Joel Damata
  email: joel.damata94@gmail.com
