apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  maxUnavailable: 33%
  selector:
    matchLabels:
      name: {{ .Release.Name }}