apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-flask
    port: 80
    targetPort: 5000
  selector:
    name: {{ .Release.Name }}
  sessionAffinity: ClientIP
